apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-user-agent
  labels:
    app: react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-user-agent
        image: rupeshrk004/react-user-agent:{{IMAGE_TAG}}
        ports:
        - containerPort: 80
